include theme.conf

#-Font rendering-
font_family JetBrainsMono Nerd Font
font_size 12

#-Shell-
shell_integration disabled

#-Cursor-
cursor_shape block
cursor_blink_interval 0

#-Visual-
window_padding_width 12
background_opacity 0.80
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
url_style curly

#-Misc-
confirm_os_window_close 0
remember_window_size no
sync_to_monitor no
